baseURL = "https://stefanoboriero.github.io"
theme = "smol"
title = "Stefano"

# Parameters
[params]
    subtitle = "A personal blog on any topic, with a strong focus on Observability and Software Engineering"
    dateFmt = "02.01.2006"
    math = true

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/posts/about"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/StefanoBoriero"
        weight = 1 

    [[menu.footer]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/stefanoboriero/"
        weight = 2

    [[menu.footer]]
        name = "E-mail"
        url = "mailto:stefano.boriero@gmail.com"
        weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
        block = true # default is false
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
